[versions]
agp = "9.2.1"
kotlin = "2.4.0"
compileSdk = "37"
material3 = "1.11.0-alpha07"
compose = "1.12.0"
publish = "0.37.0"

[libraries]
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }

kotlin-multiplatform = { module = "org.jetbrains.kotlin.multiplatform:org.jetbrains.kotlin.multiplatform.gradle.plugin", version.ref = "kotlin" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform" }
multiplatform-android-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
gradle-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }